{% set name = "feast" %}
{% set version = "0.3.0" %}
{% set sha256 = "a43004925717924ec5dd56d95a9d35e18adabb696d3b3fc4530c8e50d34aff84" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.ecs.umass.edu/~polizzi/feast/m3-0/feast_3.0.tgz
  sha256: {{ sha256 }}

build:
  number: 100
  skip: true  # [win]
  features:
    - blas_{{ variant }}


requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*

test:
  commands:
    - test -f "${PREFIX}/lib/libfeast.a"
    - test -f "${PREFIX}/lib/libfeast_banded.a"
    - test -f "${PREFIX}/lib/libfeast_dense.a"
    - test -f "${PREFIX}/lib/libfeast_sparse.a"
    - test -f "${PREFIX}/lib/libpfeast.a"
    - test -f "${PREFIX}/lib/libpfeast_banded.a"
    - test -f "${PREFIX}/lib/libpfeast_dense.a"
    - test -f "${PREFIX}/lib/libpfeast_sparse.a"

about:
  home: http://www.feast-solver.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: 3.0/LICENSE
  summary: 'High-Performance Numerical Library for Solving Eigenvalue Problems'
  description: |
    The FEAST eigensolver package is a free high-performance numerical library
    for solving the Hermitian and non-Hermitian eigenvalue problems, and obtaining
    all the eigenvalues and (right/left) eigenvectors within a given search interval
    or arbitrary domain in the complex plane. Its originality lies with a new
    transformative numerical approach to the traditional eigenvalue algorithm 
    design - the FEAST algorithm. The algorithm takes its inspiration from the
    density-matrix representation and contour integration technique in quantum
    mechanics. It contains elements from complex analysis, numerical linear algebra
    and approximation theory, and it can be defined as an optimal subspace iteration
    method using approximate spectral projectors. FEAST's main building block is a
    numerical quadrature computation consisting of solving independent linear systems
    along a complex contour, each with multiple right hand sides. A Rayleigh-Ritz 
    procedure is then used to generate a reduced dense eigenvalue problem orders of
    magnitude smaller than the original one. The FEAST eigensolver combines simplicity
    and efficiency and it offers many important capabilities for achieving high
    performance, robustness, accuracy, and scalability on parallel architectures. 
  doc_url: http://www.ecs.umass.edu/~polizzi/feast/doc.htm
  dev_url: http://www.ecs.umass.edu/~polizzi/feast/index.htm

extra:
  recipe-maintainers:
    - basnijholt
