{% set name = "pandoc-xnos" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03f83e6e5d77e5bf04e259fd3ee6c0752506465e9cddd56b71baaf9cb6a86450

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandocfilters
    - psutil

test:
  imports:
    - pandocxnos

about:
  home: https://github.com/tomduck/pandoc-xnos/
  license: MIT
  license_family: GPL
  license_file: LICENSE
  summary: 'Library code for pandoc-fignos/eqnos/tablenos.'
  description: |
    pandoc-xnos provides library code for the pandoc-fignos/eqnos/tablenos filters.
  doc_url: https://github.com/tomduck/pandoc-xnos
  dev_url: https://github.com/tomduck/pandoc-xnos

extra:
  recipe-maintainers:
    - basnijholt
