{% set name = "pandoc-fignos" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5cd1a3049b22587541615238b4264b01679c5a6aa2312c257d21bfdfa6fdb8d7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandoc-xnos

about:
  home: https://github.com/tomduck/pandoc-fignos/
  license: MIT
  license_family: GPL
  license_file: LICENSE
  summary: 'A pandoc filter for numbering figures and figure references.'
  description: |
    pandoc-fignos is a pandoc filter for numbering figures and figure
    references when converting markdown documents to other formats.
  doc_url: https://github.com/tomduck/pandoc-fignos
  dev_url: https://github.com/tomduck/pandoc-fignos

extra:
  recipe-maintainers:
    - basnijholt
