# {% set version = "0.27.12" %}

package:
  name: klayout
  version: {{ version }}

source:
  url: https://github.com/KLayout/klayout/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6ef5e6ae5ea387618663949a1efa105406aeb36db2d18d89eff0345955aae979
  patches:
    - force-python-dynamic-link.patch

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('expat') }}  # [linux]
    - {{ cdt('libpng') }}  # [linux]

  host:
    - ruby >2
    - qt >=5.0,<6.0
  run:
    - python
    - zlib
    - libpython-static
    - expat  # [win]
    - curl  # [win]
    - pthreads-win32  # [win]

test:
  commands:
    - klayout -v

about:
  home: https://www.klayout.de/
  summary: "Your Mask Layout Friend"
  description: |
    - View: Fast and accurate viewing of huge layout files
    - Edit: Draw, modify and transform hierarchical layout
    - Generate: Script layout generators, PCells and layout transformation tools
    - Analyze: Search, verify, and measure layout and code analysis scripts
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://www.klayout.de/doc.html
  dev_url: https://github.com/KLayout/klayout

extra:
  recipe-maintainers:
    - basnijholt
    # TODO: ask the folks below to be maintainers
    # - curtisma
    # - klayoutmatthias
    # - proppy
    # - flaport
    # - joamatab
